### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by ak9250** [auspicious3000/autovc#1]
AttributeError                            Traceback (most recent call last)
<ipython-input-21-1ec7926c8eff> in <module>()
     15     c = spect[1]
     16     print(name)
---> 17     waveform = wavegen(model, c=c)
     18     librosa.output.write_wav(name+'.wav', waveform, sr=16000)

/content/autovc/synthesis.py in wavegen(model, c, tqdm)
     46 
     47     """
---> 48     c = c.numpy()
     49 
     50     model.eval()

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

**Comment by auspicious3000** [comment]
Error fixed

**Comment by ak9250** [comment]
thanks i also added 
#g_checkpoint = torch.load('autovc.ckpt')
g_checkpoint = torch.load('/content/autovc/autovc.ckpt',map_location='cuda:0')
in converter.ipynb line 18 which was giving a error
also how can i test this with my own source and target wav files?

**Comment by auspicious3000** [comment]
As authors, we certainly appreciate your concerns, and we thank you for your interest in our method. On the other hand, as researchers from IBM, while we are committed to ensuring that our results can be verified and reproduced, we also must balance those considerations against potential misuse of the technology, per our company's policy. We believe that withholding a small fraction of code is a workable compromise that allows the community to nonetheless easily understand and evaluate the method. If you'd like to discuss further, please contact us at yang.zhang2@ibm.com.
