### ISSUE TITLE
Tranning is too slow

### ISSUE THREAD

**Issue by 1015720437** [auspicious3000/autovc#23]
I used a training set of 400 speaker each of them have 350 senten .Training is very slow.
is that too big?
What is the training set you use?
Can you tell me?

**Comment by auspicious3000** [comment]
VCTK. You can find all these details in the paper.

**Comment by 1015720437** [comment]
> VCTK. You can find all these details in the paper.

How many epochs the model ran in the demo. My training is very slow, it accounts for 17G gpu memory. But in the case of reducing the data set, one still takes an hour. I saw that you wrote epochs in the hyperparameter file is 3000. How long did it take you to train?
