### ISSUE TITLE
Dataset Size for Training

### ISSUE THREAD

**Issue by jacob-mink** [auspicious3000/autovc#32]
I have seen in #27 that 300k steps is necessary for training. Do the original results use the entirety of the VCTK dataset with 9/10 train, 1/10 test as in the paper, or do they use only a subset of the VCTK dataset?

Also, just to clarify, a step or iteration is one batch being passed through the network, correct? i.e. If the dataset is of size 10000, then you get 5000 steps (or iterations) out of it on a batch size of 2 in one epoch.

**Comment by auspicious3000** [comment]
The only use a subset.

Yes.

**Comment by jacob-mink** [comment]
The Chou et. al. set?
