### ISSUE TITLE
why the quality of the demo page has difference with your new paper?

### ISSUE THREAD

**Issue by azraelkuan** [auspicious3000/autovc#36]
i listen all the demo wavs in these pages. 

this is the new paper: https://auspicious3000.github.io/icassp_2020_demo/
this paper: https://auspicious3000.github.io/autovc-demo/

**Comment by auspicious3000** [comment]
The new paper improved the autovc by controlling the pitch. The old paper focuses on timbre conversion, but the new paper introduces pitch conversion.

**Comment by azraelkuan** [comment]
@auspicious3000 what i mean is that the demo in [https://auspicious3000.github.io/autovc-demo/ ] is much better than the demo[autovc] in  https://auspicious3000.github.io/icassp_2020_demo/

**Comment by auspicious3000** [comment]
In order to show the improvements of the new method, we intentionally picked some problematic samples from the old paper.
