### ISSUE TITLE
The complete training code may be sent through email upon special request for non-commercial purposes.

### ISSUE THREAD

**Issue by auspicious3000** [auspicious3000/autovc#38]
Please send an email to auspicious3000@gmail.com

**Comment by maemoKKK** [comment]
repay for my Undergraduate thesis. pls send me a copy to maemo@163.com. thanks

**Comment by fairchildfzc** [comment]
Using for my course project. Can you send me a copy to fairchildfzc@hotmail.com? Thanks.

**Comment by maemoKKK** [comment]
How about your ICASSP2020 paper? is it accepted? where did you public it?

**Comment by tianlongwang** [comment]
Please send me a copy to tianlongwang13@gmail.com  Thanks!

**Comment by chufanwu** [comment]
Using for my undergraduate thesis. I would really appreciate it! Email: chufanwu15@gmail.com

**Comment by j2l** [comment]
Please send me a copy: jeanllegros@yahoo.fr

**Comment by wangydong** [comment]
using for my Undergraduate thesis. pls send me a copy to 599104642@qq.com. thanks

**Comment by sridhar9999** [comment]
siddarthabhi042@gmail.com 

Could u please send me for part of my graduation project

**Comment by AlexMessner** [comment]
Hello, I want to cover voice voncersion in my Bachelor Thesis, which won't be published.
Could you please send me the code to 1710653302@stud.fh-kufstein.ac.at?

**Comment by auspicious3000** [comment]
The upgraded version of this work has been published in ICASSP 2020 and available for viewing.

https://ieeexplore.ieee.org/document/9054734

**Comment by maemoKKK** [comment]
ni tai niu le.

**Comment by sridhar9999** [comment]
Where can view the code for this project

**Comment by sridhar9999** [comment]
I mean full training code sir

**Comment by ye2020** [comment]
> The upgraded version of this work has been published in ICASSP 2020 and available for viewing.
> 
> https://ieeexplore.ieee.org/document/9054734

Great work! The sample audios sound really good.

I am trying to reproduce your results, but it's not quite clear to me that during inferencing, how the normalized quantized log-F0 is computed, is it computed from the source speaker's utterance or from the target speaker's one?

**Comment by auspicious3000** [comment]
@ye2020 It is from the source speaker, same as in training.

**Comment by MayukhSobo** [comment]
@auspicious3000 Why are you not sending or uploading the complete code? Your claimed results are not good enough if we can't replicate it.

**Comment by auspicious3000** [comment]
For all code requests, please send an email to auspicious3000@gmail.com introducing yourself with affiliation and describing how the code will be used for your research. Thanks!

**Comment by auspicious3000** [comment]
A more advanced version of AutoVC will be published soon. It split speech into rhythm, pitch, and timbre at the same time. Paper will be available on arxiv in a few days. Here is the demo. 
https://anonymous0818.github.io/

**Comment by MayukhSobo** [comment]
@auspicious3000  What's the point of more advanced ones when the less advanced one is difficult to reproduce??
