### ISSUE TITLE
Tools to split VCTK audio

### ISSUE THREAD

**Issue by YichongLeng** [auspicious3000/autovc#39]
From your demo, it seems that some tools are used to split origin VCTK audio. Can you please share the tools?

**Comment by maemoKKK** [comment]
Do you mean VAD?

**Comment by YichongLeng** [comment]
In my understanding, VAD can split audio by silence. But how can we split the transcript too while keeping the split result of audio and transcript aligned? I wonder what is the tools used.

**Comment by auspicious3000** [comment]
Human

**Comment by YichongLeng** [comment]
Get~ Thanks for your reply~

**Comment by ma1112** [comment]
Up to my understanding AutoVC is a non-parallel training method, hence needs no transcript to train. I wonder why are you concerned about using / splitting the transcript at all.

**Comment by maemoKKK** [comment]
agree, onl TTS needs word alignments.

**Comment by syyuan1993** [comment]
@auspicious3000 
Thanks for great work and code. I tried to run the code you sent through email with 20 speakers of VCTK data and the model did not converge. My primary guessing was about preprocessing. I tried with deleting silence starts and ends of audios. It doesn't really work. What did you do for data preprocessing?

Thanks

**Comment by auspicious3000** [comment]
@syyuan1993 You can find all the details in the data preprocessing code.

**Comment by syyuan1993** [comment]
@auspicious3000 Sure. But the data samples you provided are different from the ones from VCTK dataset. For example, the silence at the start and end of all audios are removed. How did you remove the silence pieces? Did you do any more preprocessing to the .wav data? Thanks a lot!

**Comment by auspicious3000** [comment]
@syyuan1993 That should not matter. No special preprocessing is required.

**Comment by syyuan1993** [comment]
@auspicious3000 Thanks for the information. But in my experiments, the model doesn't converge once I use more audio data, for example, 20 speakers with 200 audios each person. Any suggestions?
