### ISSUE TITLE
What is the difference between L_recon and L_recon0 ?

### ISSUE THREAD

**Issue by hyzhan** [auspicious3000/autovc#5]
About L=L<sub>recon</sub> +μ * L<sub>recon0</sub> + λ * L<sub>content</sub>
The paper is not very clear, how can I get loss  L<sub>recon0</sub> ?
L<sub>recon</sub> and L<sub>recon0</sub> Are they related to the loss before and after the residual module?

**Comment by arunasank** [comment]
Did you understand this difference @hyzhan ?

**Comment by hyzhan** [comment]
> Did you understand this difference @hyzhan ?
loss before and after the residual module of melspectrum

**Comment by hyzhan** [comment]
> Did you understand this difference @hyzhan ?

loss before and after the residual module of melspectrum
