### ISSUE TITLE
What are the differences between the model hosted in this repo and the true model?

### ISSUE THREAD

**Issue by ngulya** [auspicious3000/autovc#56]
In other issues I have seen that a request to IBM (through you?) is required to get the full code.
Where to write if it's so?

**Comment by auspicious3000** [comment]
They are the same.

**Comment by ngulya** [comment]
Okay, a question from the other side)
I noticed that some inaccuracies were added to this code (not saving the model, adding noise, another metadata format), the question is why?

**Comment by auspicious3000** [comment]
The code is made as simple as possible so that it does not cause unnecessary confusion.
It is my personal habit to add a little bit of random noise to training audio. Free feel to remove it.
The test and train metadata have different format and it is very easy to figure out.

**Comment by ngulya** [comment]
Thanks for the answer and for the paper!
