### ISSUE TITLE
Very slow inference

### ISSUE THREAD

**Issue by samialsindi** [auspicious3000/autovc#58]
Hi, impressive work!
I've tried to add a new speaker into the model (using your pretrained models), went through the make spectrogram and make metadata steps; had to edit the train.pkl to fit the same structure as the metadata.pkl.
I think I've done everything right but it is taking 1 hour to produce a 10 second inference on a GPU instance (p2.xlarge).
Is this expected? Is there something I'm doing very wrong?

Thanks in advance

**Comment by auspicious3000** [comment]
It is due to the wavenet vocoder. You can make it fast by using other vocoders.
