### ISSUE TITLE
How content loss is implemented?

### ISSUE THREAD

**Issue by ahrzb** [auspicious3000/autovc#62]
In the paper there is a content_loss which is computed based on the speaker encoder on reconstructed audio, but I don't find any mention of that in this implementation, am I missing something?

**Comment by auspicious3000** [comment]
https://github.com/auspicious3000/autovc/blob/master/solver_encoder.py#L95

**Comment by ahrzb** [comment]
Thanks, I was missing that entirely :see_no_evil:
