### ISSUE TITLE
How to generate the pretrained model/checkpoint files?

### ISSUE THREAD

**Issue by KevinHua** [auspicious3000/autovc#65]
There are three pretrained files:
autovc.ckpt: autovc model.
3000000-BL.ckpt: D-VECTOR.
checkpoint_step001000000_ema.pth: wavenet

The first one could be saved in solver_encoder.py as described in an previous issue. And how to generate the last two files?
Thanks a lot.

**Comment by auspicious3000** [comment]
The 2nd one is for the speaker verification model, and the 3rd one is for the vocoder, neither are part of this project.

**Comment by KevinHua** [comment]
Gotted it. The file checkpoint_step001000000_ema.pth is r9y9 wavenet_vocoder's model and I'll try it. And could you please give some tips more about the the speaker verification model, git repo or papers? 
Thanks.

**Comment by auspicious3000** [comment]
Yes. that model is described and cited in our paper.
