### ISSUE TITLE
About decoder mismatch

### ISSUE THREAD

**Issue by wade3han** [auspicious3000/autovc#7]
Hi, I have a question about the decoder mismatch between code and the paper.

In the paper, it used 3 LSTM layers after 3 convnorm layers.
However in the code, it used 1 LSTM, 3 convnorm layers are following after, and 2 LSTM layers are used next.

Is this mismatch intended? I am wondering which implementation is correct.
Thanks.

**Comment by auspicious3000** [comment]
Code is more up-to-date
