### ISSUE TITLE
In train.py where are the checkpoints saved? 

### ISSUE THREAD

**Issue by paklau99988** [auspicious3000/autovc#75]
I am running training, but see no checkpoints or PT files.
Thanks

**Comment by auspicious3000** [comment]
Yes. You need to add the code for saving checkpoints.

**Comment by paklau99988** [comment]
I added this, but file size make wrong:
`torch.save({'model': self.G.state_dict(), 'optimizer': self.g_optimizer.state_dict()}, 'autovc.ckpt')    `

And get:
`enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory`

**Comment by auspicious3000** [comment]
This looks like a pytorch related problem. You can refer to pytorch documentation for more details.
