### ISSUE TITLE
Error(s) in loading state_dict for Generator: 	size mismatch for encoder.lstm.weight_ih_l0: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([128, 512])

### ISSUE THREAD

**Issue by paklau99988** [auspicious3000/autovc#77]
Helo,
After trainig I try load model. I did not change any parameter. 

```
Error(s) in loading state_dict for Generator:
	size mismatch for encoder.lstm.weight_ih_l0: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([128, 512])
```
What make wrong?

**Comment by paklau99988** [comment]
I had to change the code to:
`G = Generator(**16**,256,512,32).eval().to(device) # (dim_neck, dim_emb, dim_pre, freq):`
Instead of:
`G = Generator(**32**,256,512,32).eval().to(device) # (dim_neck, dim_emb, dim_pre, freq):`

**Comment by JohnHerry** [comment]
The same problem. What is the final solution?

**Comment by JohnHerry** [comment]
I am trying to retrain with  python main.py --dim_neck=32 --freq=32 ;  Maybe that is the same inputs shape with pretrained model.

**Comment by auspicious3000** [comment]
Yes. There might be some parameter discrepancies after the 2nd major repo update.

**Comment by ynalcakan** [comment]
So what is the solution? Will you make a correction on the repo? The code is still not reproducible with this the current version.

**Comment by auspicious3000** [comment]
@ynalcakan To load a Pytorch checkpoint, the hyperparameters have to match. You need to set the corresponding hyperparameters before loading a Pytorch checkpoint. For example, you can try setting --dim_neck=32 --freq=32
