### ISSUE TITLE
Where is metadata.pkl created for my own dataset? 

### ISSUE THREAD

**Issue by paklau99988** [auspicious3000/autovc#78]
I do not want to use the metadata.pkl you provided, I want to generate a new one. 

Conversion.ipynb expects this:
`metadata = pickle.load(open('metadata.pkl', "rb"))`

But make_metadata.py never created metadata.pkl, it creates train.pkl. 

So how do I generate metadata.pkl? 
Thanks

**Comment by nischal-sanil** [comment]
Hi @paklau99988 ,

I currently have the same question. Where you able to find out how the `metadata.pkl` is generated.

**Comment by chandrakanthlns** [comment]
Hi @nischal-sanil ,

Did you find the answer to this? Even I am having this doubt about creating metadata.pkl with our own dataset. 

make_metadata.py creates train.pkl.

Can someone tell the data pickled inside the metadata.pkl?
