### ISSUE TITLE
I wrote a single Jupyter notebook to reproduce the results, but all I get is silence, please help

### ISSUE THREAD

**Issue by paklau99988** [auspicious3000/autovc#79]
Dear author, 
I trying very hard to get this project work. I finally create  single notebook (https://github.com/paklau99988/audio00), where I also generate metadata.pkl and everything else needed for the project. Can you please take a look and tell me what am I doing wrong? 

I use this corpus:
https://datashare.is.ed.ac.uk/handle/10283/2211

Training log:
```
Elapsed [14:43:55], Iteration [566890/1000000], G/loss_id: 0.0187, G/loss_id_psnt: 0.0184, G/loss_cd: 0.0002
Elapsed [14:43:56], Iteration [566900/1000000], G/loss_id: 0.0179, G/loss_id_psnt: 0.0177, G/loss_cd: 0.0002
Elapsed [14:43:57], Iteration [566910/1000000], G/loss_id: 0.0169, G/loss_id_psnt: 0.0167, G/loss_cd: 0.0003
Elapsed [14:43:59], Iteration [566920/1000000], G/loss_id: 0.0188, G/loss_id_psnt: 0.0187, G/loss_cd: 0.0002
Elapsed [14:44:00], Iteration [566930/1000000], G/loss_id: 0.0325, G/loss_id_psnt: 0.0324, G/loss_cd: 0.0002
```

The sample audio is here: https://github.com/paklau99988/audio00

Thanks

**Comment by DominikKoller** [comment]
Did you make any progress on this? I'm having the same issues, I think it might have to do with #4

**Comment by paklau99988** [comment]
No make progress, bad documentation.

**Comment by Abhay242** [comment]
Did you use the trained models given by the author or you trained one yourself?

**Comment by paklau99988** [comment]
I trained from scratch, no work at all. Not continue.

**Comment by JohnHerry** [comment]
> Dear author,
> I trying very hard to get this project work. I finally create single notebook (https://github.com/paklau99988/audio00), where I also generate metadata.pkl and everything else needed for the project. Can you please take a look and tell me what am I doing wrong?
> 
> I use this corpus:
> https://datashare.is.ed.ac.uk/handle/10283/2211
> 
> Training log:
> 
> ```
> Elapsed [14:43:55], Iteration [566890/1000000], G/loss_id: 0.0187, G/loss_id_psnt: 0.0184, G/loss_cd: 0.0002
> Elapsed [14:43:56], Iteration [566900/1000000], G/loss_id: 0.0179, G/loss_id_psnt: 0.0177, G/loss_cd: 0.0002
> Elapsed [14:43:57], Iteration [566910/1000000], G/loss_id: 0.0169, G/loss_id_psnt: 0.0167, G/loss_cd: 0.0003
> Elapsed [14:43:59], Iteration [566920/1000000], G/loss_id: 0.0188, G/loss_id_psnt: 0.0187, G/loss_cd: 0.0002
> Elapsed [14:44:00], Iteration [566930/1000000], G/loss_id: 0.0325, G/loss_id_psnt: 0.0324, G/loss_cd: 0.0002
> ```
> 
> The sample audio is here: https://github.com/paklau99988/audio00
> 
> Thanks

There is a bug in the source that you should fix before your training.  In solver_encoder.py, line 90, 91, results should be squeezed before they are used to compute loss.  
Reference: https://github.com/auspicious3000/autovc/issues/20
Good luck!

**Comment by PeijiYang** [comment]
> In solver_encoder.py, line 90, 91, results should be squeezed before they are used to compute loss.

@JohnHerry Can you specify how to modify this part of the code.

**Comment by JohnHerry** [comment]
> > In solver_encoder.py, line 90, 91, results should be squeezed before they are used to compute loss.
> 
> @JohnHerry Can you specify how to modify this part of the code.

You, Please, print out the shape of data and predicted data before compute the loss, then you can understand what I mean.
