### ISSUE TITLE
pickle error?

### ISSUE THREAD

**Issue by ztzhang** [auspicious3000/autovc#8]
Hi, I'm using python 3.7.3 with numpy 1.16.4 and is experiencing the following error when loading meta data:
``
   metadata = pickle.load(open('metadata.pkl', "rb"))

Traceback (most recent call last):
  File " stdin ", line 1, in  module 
_pickle.UnpicklingError: invalid load key, '\x0a'.
``
I guess this might be an encoding mismatch ('ASCII' by default) or a numpy version mismatch.
Would it be possible for you to share a npy/npz version of the metadata.pkl? Thanks!

**Comment by auspicious3000** [comment]
This is probably due to numpy version mismatch. The metadata is a python list of lists of texts and numpy arrays. Saving using npy/npz might cause problems.

**Comment by ztzhang** [comment]
would you mind adding a numpy version number in readme then? 
Also if there are texts, it would be great if you could share the default encoding for your python environment.
Thanks!

**Comment by auspicious3000** [comment]
numpy version 1.16.4
default encoding utf-8
