### ISSUE TITLE
Where is the "Deconv Layer" in figure 3(d) in your paper?

### ISSUE THREAD

**Issue by gnipping** [auspicious3000/autovc#83]
I retrain the model in VCTK corpus following the training steps in your paper. However, I only get noise in my generated voice.  I have a quesion in the file "metadata.pkl" in your project. Does the mel feature matrix in this file has already passed  "Deconv Layer"?

**Comment by auspicious3000** [comment]
No.

**Comment by gnipping** [comment]
So is the "Deconve layer" in your paper already include in "wavenet_vocoder"?

**Comment by auspicious3000** [comment]
Yes

**Comment by gnipping** [comment]
OK, thank you very much!
