### ISSUE TITLE
Getting the voice conversion work on short segments (~120 ms)

### ISSUE THREAD

**Issue by rppravin** [auspicious3000/autovc#86]
Thanks for the code!

In the default settings of the code, training uses ~2 sec segments (with 1:16 downsampling at the bottle neck layer).

Is it possible to modify the code to get voice conversion working for ~120 ms segments?

Thanks in advance,
Pravin

**Comment by auspicious3000** [comment]
In this case, you don't need to modify the code. Just pad your segments to the nearest multiple of 16 frames.
