### ISSUE TITLE
Pretrained model for speaker encoder

### ISSUE THREAD

**Issue by anitaweng** [auspicious3000/autovc#99]
Hi, it is a nice work.

I am trying to reproduce the result of vctk.
I want to ask about if the [**pretrained model of speaker encoder**](https://drive.google.com/file/d/1ORAeb4DlS_65WDkQN6LHx5dPyCM5PAVV/view) provided in your readme is trained on the combination of VoxCeleb1 and Librispeech as mentioned in your paper, or is just trained on a small set of vctk speakers?
Also, is the [**pretrained model of wavenet vocoder** ](https://drive.google.com/file/d/1Zksy0ndlDezo9wclQNZYkGi_6i7zi4nQ/view) trained on the whole vctk dataset or only a small part of it?

Thank a lot!

**Comment by auspicious3000** [comment]
The GE2E wouldn't work well if trained on small dataset.

**Comment by anitaweng** [comment]
So the provided pretrained speaker encoder is trained on the combination of VoxCeleb1 and Librispeech, and the provided wavenet vocoder is just trained on vctk.
Am I right?

**Comment by anitaweng** [comment]
Thanks for your reply.
Then If I train a new autovc model with the pretrained speaker encoder and pretrained wavenet model on vctk dataset with your original setting, can I reproduce a well results as well as yours for unseen vctk speakers?

**Comment by auspicious3000** [comment]
Ideally yes.

**Comment by anitaweng** [comment]
Thanks for your reply.
